### ISSUE TITLE
I don't get the parameters while icheck is enabled

### ISSUE THREAD

**Issue by patatoid** [cubus/icheck-rails#6]
Using icheck, I get the right front with pretty checkboxes but while I submit the form I don't get the parameters in my controller...

Does anyone face the same issue ?

**Comment by pmalliak** [comment]
I have exactly the same issue as patatoid, when i remove the check-me it sends the right attribute on controller, but when the icheck is enabled I only get value=0 (From rails hidden input).

**Comment by mtarnovan** [comment]
@pmalliak As I said, I don't see how that could be an issue with icheck-rails, which just packages icheck for the asset pipeline. Might want to raise an issue with https://github.com/fronteed/iCheck
