### ISSUE TITLE
Deprication warning *.css.scss should be renamed to *.scss

### ISSUE THREAD

**Issue by maxgronlund** [cubus/icheck-rails#7]
DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename /home/rof/cache/bundler/ruby/2.2.0/gems/icheck-rails-1.0.2.1/vendor/assets/stylesheets/icheck/square/blue.css.scss to /home/rof/cache/bundler/ruby/2.2.0/gems/icheck-rails-1.0.2.1/vendor/assets/stylesheets/icheck/square/blue.scss.

**Comment by mtarnovan** [comment]
@maxgronlund Can you send a PR?
